services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - './backend:/var/www/html'
      - './backend/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
  php:
    image: wodby/php:8.3
    volumes:
      - './backend:/var/www/html'
  react:
    image: node:18-alpine
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node/app
    command: sh -c "npm install && npm start"
